// Local composition guidance only: no identity lookup, model call or settings
// mutation. Position in a half is not the same as facing the other subject.
// Exact built-in keys are intentional; free text may specify back-to-back,
// averted faces or another composition which must not be guessed or reversed.
const RULES = [
    [['半颗爱心', '隔空对望', '一根红线', '隔空击掌', '递出一朵花', '碰一碰鼻尖', '一边闹一边笑', '互相做鬼脸', '举杯碰杯', '一人一只小动物', '耳机分你一只', '一人一半饼干', '递来最后一口', '草莓分给你', '两杯不同口味', '一串糖葫芦', '交换便当', '接住一片落叶', '星星递给你', '拼成一朵花', '纸飞机传话'],
        'An affectionate exchange reads across the center through complementary inward head angles and an answering gesture.',
        'Angle the head toward the right, toward the partner or the exchanged object; direct this gesture inward.',
        'Angle the head toward the left, toward the partner or the exchanged object; answer the offered gesture warmly.',
        'reciprocal inward head angles, affectionate exchange, complementary response',
        'head angled right toward partner, inward gesture', 'head angled left toward partner, warm answering gesture'],
    [['左右眨眼', '偷偷模仿你', '偷偷戴上同款', '同款不同色', '日与月的呼应'],
        'Keep a mostly front-facing paired display, with subtly inward body angles and complementary responses connecting the poses.',
        'Remain mostly front-facing, with a slight body angle toward the right and a gesture for the partner to answer.',
        'Remain mostly front-facing, with a slight body angle toward the left and a distinct answering gesture.',
        'mostly front-facing pair, subtly inward body angles, complementary paired gestures',
        'mostly front-facing, body angled slightly right, initiating gesture', 'mostly front-facing, body angled slightly left, answering gesture'],
    [['悄悄牵住衣角'],
        'The small tug and the partner turning back make the connection readable.',
        'Tilt the head toward the right, accompanying the gentle inward tug.',
        'Turn the head back toward the left in response to the tug, with a shy head tilt.',
        'gentle tug, responsive backward head turn',
        'head tilted right, gentle inward tug', 'head turned back left, shy answering tilt'],
    [['替你理围巾'],
        'A caring inward lean is answered by a still, receptive head tilt.',
        'Angle the head toward the right and the scarf being adjusted.',
        'Angle the head gently toward the left, holding still for the caring gesture.',
        'caring inward lean, receptive head tilt',
        'head angled right toward shared scarf', 'head tilted left, still receptive posture'],
    [['藏在背后的小花'],
        'Keep the flower hidden while the curious partner responds to the secretive pose.',
        'Angle the head toward the right with an expectant tilt while keeping the flower behind the body.',
        'Tilt the head toward the left and lean curiously toward the hidden flower.',
        'hidden flower, secretive pose, curious partner response',
        'head angled right, expectant tilt, flower behind body', 'head tilted left, curious inward lean'],
    [['假装生气', '一边偷看一边躲'],
        'Keep the deliberately averted reaction; connect the pair through a responsive body tilt or gesture, not forced eye contact.',
        'Keep the chosen teasing, shy or mock-annoyed head angle, with the body or gesture still responding toward the right.',
        'Keep the chosen amused or bashfully averted head angle, with the body or gesture still responding toward the left.',
        'deliberately averted reaction, responsive body angles, complementary gestures',
        'chosen head angle retained, body or gesture responding right', 'chosen head angle retained, body or gesture responding left'],
    [['一边困一边闹'],
        'Preserve the sleepy-versus-energetic contrast, linked by a gentle inward lean.',
        'Keep the drowsy head droop, tilted slightly toward the partner on the right.',
        'Angle the head and lively attention-seeking gesture toward the left without waking or uncovering the partner by default.',
        'sleepy and energetic contrast, gentle inward lean',
        'drowsy head droop, slight rightward tilt', 'head angled left, lively attention-seeking gesture'],
    [['被发现的偷笑', '偷吃被发现'],
        'Make the noticed expression and the knowing response belong to the same small moment.',
        'Tilt the head slightly toward the right as this subject reacts to being noticed.',
        'Angle the head toward the left and answer the partner with an amused head tilt.',
        'caught-in-the-moment reaction, knowing partner response',
        'slight rightward head tilt, noticed reaction', 'head angled left, amused answering tilt'],
    [['一起看烟花'],
        'Keep both oriented toward the same distant fireworks, with companionable inward body leans and a nod answering the pointing gesture.',
        'Angle the head toward the shared fireworks while pointing out the display to the partner.',
        'Keep the head oriented toward the same fireworks and answer the pointing gesture with a small nod and an inward body lean.',
        'shared distant fireworks focus, companionable inward body leans, pointing-and-nod response',
        'head toward shared fireworks, pointing gesture', 'head toward same fireworks, answering nod, inward body lean'],
    [['并肩吹泡泡'],
        'The bubble drifting between the pair connects the action and response.',
        'Angle the head toward the right along the bubble path.',
        'Angle the head toward the incoming bubble from the left and answer with a playful head tilt.',
        'shared bubble path, responsive head angles',
        'head angled right along bubble path', 'head toward incoming bubble from left, answering head tilt'],
    [['共用一条围巾', '分享一把伞', '围巾里躲风'],
        'Keep the shared shelter or warmth readable through close inward body leans and softly answering head tilts.',
        'Lean gently toward the right into the shared space, keeping the existing scarf or umbrella action.',
        'Lean gently toward the left into the shared space with an answering head tilt.',
        'shared warmth or shelter, close inward body leans, answering head tilts',
        'gentle rightward body lean, shared shelter gesture', 'gentle leftward body lean, answering head tilt'],
    [['一起读一本书'],
        'Both heads incline toward the same open page, with the second reaction answering the indicated passage.',
        'Incline the head downward and inward toward the shared page while indicating the passage.',
        'Incline the head downward and inward toward that same passage, answering with a distinct head tilt.',
        'shared open-page focus, companionable lean, responsive head tilts',
        'head inclined downward and inward, passage-pointing gesture', 'head inclined toward same passage, answering head tilt'],
    [['举起同款相机'],
        'The photographer and the responding subject form one directed exchange, not two unrelated camera poses.',
        'Turn the head and raised camera toward the partner on the right.',
        'Turn the head toward the camera on the left and answer its framing with a playful pose.',
        'photographer-and-subject exchange, responsive camera pose',
        'head turned right, camera aimed toward partner', 'head turned left toward partner camera, answering pose'],
    [['融化的冰淇淋'],
        'The offered napkin answers the problem with the melting ice cream.',
        'Keep the head inclined toward the ice cream, with a small responsive tilt toward the helping partner on the right.',
        'Angle the head toward the left and the melting ice cream while offering the napkin.',
        'shared melting-ice-cream focus, caring napkin response',
        'head inclined toward ice cream, responsive rightward tilt', 'head angled left toward ice cream, napkin-offering gesture'],
    [['一起捧雪花'],
        'Keep each snowflake as its own small focus, linked through companionable inward body leans and answering cupped gestures.',
        'Incline the head toward this subject\'s snowflake, with a slight body lean toward the right.',
        'Incline the head toward this subject\'s snowflake, with a slight body lean toward the left and an answering cupped gesture.',
        'individual snowflake focus, inward body leans, answering cupped gestures',
        'head inclined toward own snowflake, slight rightward body lean', 'head inclined toward own snowflake, slight leftward body lean, answering gesture'],
    [['花瓣落在头顶'],
        'The unnoticed petal and the partner pointing it out create a small responsive moment.',
        'Tilt the head toward the partner on the right in response, leaving the unnoticed petal in place.',
        'Angle the head toward the left and the petal on the partner\'s head while pointing it out.',
        'unnoticed petal, pointing partner, responsive head tilt',
        'head tilted right toward partner, petal retained', 'head angled left toward partner petal, pointing gesture'],
    [['夏夜捕萤'],
        'Keep the fireflies as the focus; connect the pair through the shared firefly trail and responsive body leans.',
        'Orient the head along the nearby firefly trail, with a companionable body lean toward the right.',
        'Orient the head toward the other firefly on that shared trail, with an answering body lean toward the left.',
        'shared firefly trail, distinct firefly focus, companionable body leans',
        'head along nearby firefly trail, rightward body lean', 'head toward other firefly, leftward answering body lean'],
    [['雨后踩水花'],
        'Connect the playful splash to the partner\'s reaction while preserving a natural recoil.',
        'Angle the head toward the partner on the right while making the small inward splash.',
        'React toward the splash arriving from the left, with a playful head tilt and natural body recoil.',
        'splash-and-reaction exchange, playful recoil',
        'head angled right toward partner, inward splash', 'head toward splash from left, playful tilt, natural recoil'],
    [['同一阵风'],
        'Keep both oriented into the same breeze; connect the pair through complementary bracing gestures and companionable body angles.',
        'Keep the lifted head oriented into the breeze, with a small body lean toward the partner on the right.',
        'Keep the head oriented into the same breeze at a different tilt, answering with a bracing gesture toward the shared space.',
        'same-breeze orientation, complementary head tilts, companionable body angles',
        'lifted head into breeze, slight rightward body lean', 'head into same breeze, different head tilt, answering bracing gesture'],
    [['两边同一片海'],
        'Keep the shared sea setting while making the two seashell displays answer one another.',
        'Keep the head comfortably toward the sea or slightly inward, presenting the shell toward the partner on the right.',
        'Keep the head comfortably toward the sea or slightly inward, answering the shell display toward the left.',
        'shared sea setting, reciprocal seashell display, relaxed companionable angles',
        'relaxed sea-facing or inward head angle, shell offered right', 'relaxed sea-facing or inward head angle, answering shell offered left'],
];

const COVERING_RULE = 'Retain supplied eye coverings and any specified closed-eye expression; convey the response through head angle, body angle or gesture when eyes are hidden.';
const text = value => typeof value === 'string' ? value.trim() : '';

export function coupleInteractionDirection(settings = {}) {
    const interaction = text(settings?.interaction);
    // Even an apparently unrelated user direction may contain a deliberate
    // pose. Do not parse or override free-form authorial instructions.
    const rule = text(settings?.direction) ? null : RULES.find(row => row[0].includes(interaction));
    const scene = rule?.[1] || 'Follow the supplied interaction and user direction, including any back-to-back or averted orientation. Make the pair respond through compatible gestures, shared focus or contact; do not replace the chosen orientation with forced eye contact.';
    const roles = rule ? rule.slice(2, 4) : [
        'Keep the left subject\'s user-directed orientation and connect its gesture to the partner\'s response.',
        'Keep the right subject\'s user-directed orientation and answer the partner through a compatible gesture.',
    ];
    const tagScene = rule?.[4] || 'user-directed orientation retained, complementary paired response, shared action';
    const tagRoles = rule ? rule.slice(5, 7) : [
        'user-directed orientation retained, initiating or responsive partner gesture',
        'user-directed orientation retained, complementary partner response',
    ];
    return {
        scene: `${scene} Explicit user direction takes precedence. ${COVERING_RULE}`,
        roles,
        // Bare positive tags cannot express a conditional covering rule:
        // preserve actual coverings in the owning subject's detail channel.
        tags: { scene: tagScene, roles: tagRoles },
    };
}
