import * as split_cgImageCore from './cgImageCore.js';
import * as split_cgImageActions from './cgImageActions.js';
// 以下导出已搬到 generation/cgImageCore.js、generation/cgImageActions.js，这里原样转发，调用方不用改。
export const IMAGE_GENERATION_COMMAND_NAMES = split_cgImageCore.IMAGE_GENERATION_COMMAND_NAMES;
export const imageGenerationCommand = split_cgImageCore.imageGenerationCommand;
export const imageGenerationUiState = split_cgImageCore.imageGenerationUiState;
export const sanitizeImageGenerationSlashPrompt = split_cgImageCore.sanitizeImageGenerationSlashPrompt;
export const invokeImageGeneration = split_cgImageCore.invokeImageGeneration;
export const normalizeCgImageUrl = split_cgImageCore.normalizeCgImageUrl;
export const normalizeCgImageRecord = split_cgImageCore.normalizeCgImageRecord;
export const normalizeCgImageHistory = split_cgImageCore.normalizeCgImageHistory;
export const sanitizeCgVisualText = split_cgImageCore.sanitizeCgVisualText;
export const cgImagePromptForItem = split_cgImageCore.cgImagePromptForItem;
export const cgImageTaskKey = split_cgImageCore.cgImageTaskKey;
export const cgImageReservationKey = split_cgImageCore.cgImageReservationKey;
export const isCgImageDrawing = split_cgImageCore.isCgImageDrawing;
export const cgImageStartBlockedReason = split_cgImageCore.cgImageStartBlockedReason;
export const dailyComicImagePrompt = split_cgImageCore.dailyComicImagePrompt;
export const cgImageLayerHtml = split_cgImageCore.cgImageLayerHtml;
export const cgImageVersions = split_cgImageCore.cgImageVersions;
export const handleCgHistorySwitch = split_cgImageActions.handleCgHistorySwitch;
export const cgItemSignature = split_cgImageCore.cgItemSignature;
export const cgItemInSession = split_cgImageCore.cgItemInSession;
export const captureCgImageTarget = split_cgImageCore.captureCgImageTarget;
export const isCgImageTargetCurrent = split_cgImageCore.isCgImageTargetCurrent;
export const assertCgImageTargetCurrent = split_cgImageCore.assertCgImageTargetCurrent;
export const buildCgReconceptPrompt = split_cgImageCore.buildCgReconceptPrompt;
export const reconceiveCgImagePrompt = split_cgImageCore.reconceiveCgImagePrompt;
export const cgImageProviderBar = split_cgImageCore.cgImageProviderBar;
export const cgImageProgressHtml = split_cgImageCore.cgImageProgressHtml;
export const updateCgImageProgress = split_cgImageCore.updateCgImageProgress;
export const cancelCurrentCgImage = split_cgImageCore.cancelCurrentCgImage;
export const refreshSettledCgImage = split_cgImageCore.refreshSettledCgImage;
export const refreshCgImageProviderBars = split_cgImageCore.refreshCgImageProviderBars;
export const imageGenerationUnavailableMessage = split_cgImageCore.imageGenerationUnavailableMessage;
export const refreshImageGenerationUi = split_cgImageCore.refreshImageGenerationUi;
export const indexedArchiveMatchesCurrentChat = split_cgImageCore.indexedArchiveMatchesCurrentChat;
export const resolveCgImageTargetDescriptor = split_cgImageCore.resolveCgImageTargetDescriptor;
export const selectedCgTarget = split_cgImageCore.selectedCgTarget;
export const prepareLanguageCgTarget = split_cgImageCore.prepareLanguageCgTarget;
export const DEFAULT_LANGUAGE_PORTRAIT = split_cgImageCore.DEFAULT_LANGUAGE_PORTRAIT;
export const prepareLanguagePortraitTarget = split_cgImageCore.prepareLanguagePortraitTarget;
export const preparePhotoshootTarget = split_cgImageCore.preparePhotoshootTarget;
export const renderCurrentCgMode = split_cgImageCore.renderCurrentCgMode;
export const deferCgSessionIfOriginChanged = split_cgImageCore.deferCgSessionIfOriginChanged;
export const deferCgImageIfOriginChanged = split_cgImageCore.deferCgImageIfOriginChanged;
export const abortActiveCgImageTasks = split_cgImageCore.abortActiveCgImageTasks;
export const hasPendingCgImage = split_cgImageActions.hasPendingCgImage;
export const retryPendingCgImage = split_cgImageActions.retryPendingCgImage;
export const drawSelectedCgImage = split_cgImageActions.drawSelectedCgImage;
export const clearSelectedCgImage = split_cgImageActions.clearSelectedCgImage;
export const restoreSelectedCgImageVersion = split_cgImageActions.restoreSelectedCgImageVersion;
export const handleOverlayMediaError = split_cgImageActions.handleOverlayMediaError;
export const prepareCgSendParts = split_cgImageActions.prepareCgSendParts;
export const cgEditorSendPreview = split_cgImageActions.cgEditorSendPreview;


