import * as split_overlayShell from './overlayShell.js';
import * as split_overlayManage from './overlayManage.js';
import * as split_overlayCore from './overlayCore.js';
import * as split_overlayPartial from './overlayPartial.js';
// 以下导出已搬到 ui/overlayShell.js、ui/overlayManage.js、ui/overlayCore.js、ui/overlayPartial.js，这里原样转发，调用方不用改。
export const isArchiveMobileViewport = split_overlayShell.isArchiveMobileViewport;
export const archiveMobileSafeTopFallback = split_overlayShell.archiveMobileSafeTopFallback;
export const applyArchiveMobileSafeArea = split_overlayShell.applyArchiveMobileSafeArea;
export const overlayCloseButtonFromEvent = split_overlayShell.overlayCloseButtonFromEvent;
export const closeArchiveOverlayFromUser = split_overlayShell.closeArchiveOverlayFromUser;
export const bindOverlayCloseFallback = split_overlayShell.bindOverlayCloseFallback;
export const revealArchiveOverlay = split_overlayShell.revealArchiveOverlay;
export const openOverlay = split_overlayCore.openOverlay;
export const closeOverlay = split_overlayShell.closeOverlay;
export const invalidateArchiveViewForChatNavigation = split_overlayShell.invalidateArchiveViewForChatNavigation;
export const bodyEl = split_overlayShell.bodyEl;
export const topTitle = split_overlayShell.topTitle;
export const setBackVisible = split_overlayShell.setBackVisible;
export const navigateBack = split_overlayCore.navigateBack;
export const setManageVisible = split_overlayShell.setManageVisible;
export const setRegenerateVisible = split_overlayShell.setRegenerateVisible;
export const confirmExplicitAction = split_overlayShell.confirmExplicitAction;
export const confirmExplicitActionTwice = split_overlayShell.confirmExplicitActionTwice;
export const confirmModeRegeneration = split_overlayShell.confirmModeRegeneration;
export const confirmRoomLifeRefresh = split_overlayShell.confirmRoomLifeRefresh;
export const requestCurrentArchiveImport = split_overlayCore.requestCurrentArchiveImport;
export const requestParticipantSelection = split_overlayShell.requestParticipantSelection;
export const participantRegenerationScopes = split_overlayShell.participantRegenerationScopes;
export const runParticipantRegeneration = split_overlayShell.runParticipantRegeneration;
export const requestParticipantVersions = split_overlayShell.requestParticipantVersions;
export const presentGenerationTaskResult = split_overlayCore.presentGenerationTaskResult;
export const requestCurrentArchiveFullRebuild = split_overlayCore.requestCurrentArchiveFullRebuild;
export const formatArchiveTime = split_overlayShell.formatArchiveTime;
export const loadChooserArchiveRecovery = split_overlayShell.loadChooserArchiveRecovery;
export const readableModePortals = split_overlayShell.readableModePortals;
export const showChooser = split_overlayCore.showChooser;
export const showLoading = split_overlayShell.showLoading;
export const showError = split_overlayShell.showError;
export const showMemoryImportError = split_overlayShell.showMemoryImportError;
export const updateBackgroundTaskLabel = split_overlayShell.updateBackgroundTaskLabel;
export const setBusyUi = split_overlayShell.setBusyUi;
export const setInnerLoading = split_overlayShell.setInnerLoading;
export const refreshArchiveTargetSnapshotView = split_overlayShell.refreshArchiveTargetSnapshotView;
export const showInlineError = split_overlayShell.showInlineError;
export const showInlinePreflight = split_overlayShell.showInlinePreflight;
export const openCachedOrGenerate = split_overlayCore.openCachedOrGenerate;
export const decorateReadOnlyModeUi = split_overlayShell.decorateReadOnlyModeUi;
export const refreshArchiveRecoveryView = split_overlayShell.refreshArchiveRecoveryView;
export const refreshContentRegenerationDraftView = split_overlayShell.refreshContentRegenerationDraftView;
export const refreshPartialGenerationView = split_overlayPartial.refreshPartialGenerationView;
export const openPartialTaskSession = split_overlayPartial.openPartialTaskSession;
export const saveActiveSessionEdit = split_overlayShell.saveActiveSessionEdit;
export const refreshSavedActiveSession = split_overlayPartial.refreshSavedActiveSession;
export const renderActive = split_overlayCore.renderActive;
export const handleOverlayClick = split_overlayCore.handleOverlayClick;
export const handleOverlayChange = split_overlayCore.handleOverlayChange;


