import * as split_roomProfile from './roomProfile.js';
import * as split_roomPets from './roomPets.js';
import * as split_roomLayout from './roomLayout.js';
import * as split_roomParticipantData from './roomParticipantData.js';
import * as split_roomLife from './roomLife.js';
import * as split_roomData from './roomData.js';
import * as split_roomRender from './roomRender.js';
import * as core_modesBridge from '../core/modesBridge.js';
import * as generation_modesBridge from '../generation/modesBridge.js';
// 以下导出已搬到 modes/roomProfile.js、modes/roomPets.js、modes/roomLayout.js、modes/roomParticipantData.js、modes/roomLife.js、modes/roomData.js、modes/roomRender.js，这里原样转发，调用方不用改。
export const ROOM_PET_SPECIES = split_roomPets.ROOM_PET_SPECIES;
export const roomNarrativeClaimsSharedHistory = split_roomProfile.roomNarrativeClaimsSharedHistory;
export const normalizeRoomVisualProfile = split_roomProfile.normalizeRoomVisualProfile;
export const normalizeRoomPetSpecies = split_roomPets.normalizeRoomPetSpecies;
export const normalizeRoomPets = split_roomPets.normalizeRoomPets;
export const roomRequiredPetSpecies = split_roomPets.roomRequiredPetSpecies;
export const roomNeedsSchemaUpgrade = split_roomData.roomNeedsSchemaUpgrade;
export const normalizeRoom = split_roomData.normalizeRoom;
export const roomCandidateRepairSlots = split_roomData.roomCandidateRepairSlots;
export const applyRoomTextRepairs = split_roomData.applyRoomTextRepairs;
export const projectRoomProgress = split_roomData.projectRoomProgress;
export const generateRoomWithRepair = split_roomData.generateRoomWithRepair;
export const compactRoomExisting = split_roomData.compactRoomExisting;
export const roomIncrementPrompt = split_roomData.roomIncrementPrompt;
export const normalizeRoomIncrementPatch = split_roomData.normalizeRoomIncrementPatch;
export const roomSpaceKey = split_roomData.roomSpaceKey;
export const roomObjectKey = split_roomData.roomObjectKey;
export const roomObjectAllowedIncrement = split_roomData.roomObjectAllowedIncrement;
export const roomObjectUsesIncrement = split_roomData.roomObjectUsesIncrement;
export const mergeRoomIncremental = split_roomData.mergeRoomIncremental;
export const refreshRoomFigure = split_roomData.refreshRoomFigure;
export const generateRoomIncrementalWithRepair = split_roomData.generateRoomIncrementalWithRepair;
export const localDateKey = split_roomLife.localDateKey;
export const parseClockMinutes = split_roomLife.parseClockMinutes;
export const formatClockMinutes = split_roomLife.formatClockMinutes;
export const roomBlueprintPayload = split_roomLife.roomBlueprintPayload;
export const roomLifePrompt = split_roomLife.roomLifePrompt;
export const normalizeRoomVisualState = split_roomLife.normalizeRoomVisualState;
export const normalizeTemporaryRoomObjects = split_roomLife.normalizeTemporaryRoomObjects;
export const normalizeRoomLifePlan = split_roomLife.normalizeRoomLifePlan;
export const fallbackRoomLifePlan = split_roomLife.fallbackRoomLifePlan;
export const roomLifeBeat = split_roomLife.roomLifeBeat;
export const roomLifeUsesDifferentBlueprint = split_roomLife.roomLifeUsesDifferentBlueprint;
export const roomPreservedLifeHtml = split_roomLife.roomPreservedLifeHtml;
export const ensureRoomLifePlan = split_roomRender.ensureRoomLifePlan;
export const roomDaypartState = split_roomLayout.roomDaypartState;
export const roomClockText = split_roomLayout.roomClockText;
export const roomSceneClass = split_roomLayout.roomSceneClass;
export const roomLayoutVariant = split_roomLayout.roomLayoutVariant;
export const roomObjectPlacement = split_roomLayout.roomObjectPlacement;
export const roomObjectLayout = split_roomLayout.roomObjectLayout;
export const roomObjectIconHtml = split_roomLayout.roomObjectIconHtml;
export const roomObjectLayoutButtonHtml = split_roomLayout.roomObjectLayoutButtonHtml;
export const roomLayoutCss = split_roomLayout.roomLayoutCss;
export const roomCurrentSlot = split_roomRender.roomCurrentSlot;
export const selectedRoomSpace = split_roomRender.selectedRoomSpace;
export const selectedRoomObject = split_roomRender.selectedRoomObject;
export const stopRoomClock = split_roomRender.stopRoomClock;
export const startRoomClock = split_roomRender.startRoomClock;
export const roomTemporaryPlacement = split_roomLayout.roomTemporaryPlacement;
export const roomObjectVisualKind = split_roomLayout.roomObjectVisualKind;
export const roomMotifToken = split_roomLayout.roomMotifToken;
export const roomPetPlacement = split_roomLayout.roomPetPlacement;
export const roomPetNodeHtml = split_roomLayout.roomPetNodeHtml;
export const roomPetSummaryHtml = split_roomLayout.roomPetSummaryHtml;
export const roomObjectSafeForPresentation = split_roomLayout.roomObjectSafeForPresentation;
export const roomDeepAvailability = split_roomLayout.roomDeepAvailability;
export const openRoomDeepMode = split_roomRender.openRoomDeepMode;
export const returnToRoomFromDeep = split_roomRender.returnToRoomFromDeep;
export const renderRoom = split_roomRender.renderRoom;
export const roomSelectSpace = split_roomRender.roomSelectSpace;
export const roomFindPresence = split_roomRender.roomFindPresence;
export const roomSelect = split_roomRender.roomSelect;
export const roomPresenceNext = split_roomRender.roomPresenceNext;
export const normalizeRoomResidents = split_roomParticipantData.normalizeRoomResidents;
export const preserveRoomLinkedContent = split_roomData.preserveRoomLinkedContent;
export const normalizeRoomParticipantsLifePlan = split_roomLife.normalizeRoomParticipantsLifePlan;
export const roomParticipantSlots = split_roomLife.roomParticipantSlots;
export const roomSelectParticipant = split_roomRender.roomSelectParticipant;
export const renderRoomParticipants = split_roomRender.renderRoomParticipants;

// 重构清单 C-3（r84.98）：把 core 层要用的函数登记到 core/modesBridge.js（core 不再 import 本文件）。
core_modesBridge.registerModesBridge({ renderRoom });
// 重构清单 C-4（r84.110）：把生成层要用的函数登记到 generation/modesBridge.js（生成层不再 import 本文件）。
generation_modesBridge.registerGenerationModesBridge({ roomNarrativeClaimsSharedHistory, roomNeedsSchemaUpgrade, normalizeRoom, projectRoomProgress, generateRoomWithRepair, refreshRoomFigure, generateRoomIncrementalWithRepair, ensureRoomLifePlan, renderRoom, preserveRoomLinkedContent });
