import * as split_independentApiConfig from './independentApiConfig.js';
import * as split_independentApiRequest from './independentApiRequest.js';
// 以下导出已搬到 core/independentApiConfig.js、core/independentApiRequest.js，这里原样转发，调用方不用改。
export const PROFILE_ONE_CLICK_UI_VERSION = split_independentApiConfig.PROFILE_ONE_CLICK_UI_VERSION;
export const connectionManagerHasProfileSecrets = split_independentApiConfig.connectionManagerHasProfileSecrets;
export const connectionManagerSupportsRequestOverrides = split_independentApiConfig.connectionManagerSupportsRequestOverrides;
export const assertConnectionManagerProfileSupport = split_independentApiConfig.assertConnectionManagerProfileSupport;
export const normalizeManualApiBaseUrl = split_independentApiConfig.normalizeManualApiBaseUrl;
export const manualApiHeadersJson = split_independentApiConfig.manualApiHeadersJson;
export const apiConfigurationFingerprint = split_independentApiConfig.apiConfigurationFingerprint;
export const manualModelCacheKey = split_independentApiConfig.manualModelCacheKey;
export const looksLikeHtmlResponse = split_independentApiConfig.looksLikeHtmlResponse;
export const readBoundedJsonResponse = split_independentApiConfig.readBoundedJsonResponse;
export const assertManualApiCredentialTransport = split_independentApiConfig.assertManualApiCredentialTransport;
export const extractManualModelIds = split_independentApiConfig.extractManualModelIds;
export const extractIndependentResponseContent = split_independentApiConfig.extractIndependentResponseContent;
export const responseShapeSummary = split_independentApiConfig.responseShapeSummary;
export const payloadHasProviderError = split_independentApiConfig.payloadHasProviderError;
export const assertIndependentResponsePayload = split_independentApiConfig.assertIndependentResponsePayload;
export const manualStreamCompletionInfo = split_independentApiConfig.manualStreamCompletionInfo;
export const assertManualStreamComplete = split_independentApiConfig.assertManualStreamComplete;
export const transportFailureSummary = split_independentApiConfig.transportFailureSummary;
export const readProfileCompletion = split_independentApiConfig.readProfileCompletion;
export const fetchManualApiModels = split_independentApiRequest.fetchManualApiModels;
export const requestManualApiCompletion = split_independentApiRequest.requestManualApiCompletion;


