// Heartbeat Memories r35 modular runtime.
// Extracted from r34 without changing archive/cache storage contracts.
import * as core_deferredCommitStore from './deferredCommitStore.js';

export const state = {
  runtimeLifecycleEpoch: 0,
  apiConfigurationEpoch: 0,
  manualApiKey: '',
  busy: false,
  activeMode: null,
  activeSession: null,
  contentManagerOpen: false,
  roomClockTimer: 0,
  phoneClockTimer: 0,
  endingEasterEggTimer: 0,
  endingEasterEggRuntime: null,
  archiveViewLevel: 'library',
  roomLifeRefreshPromise: null,
  roomLifeRefreshOrigin: null,
  activeTaskAbortController: null,
  activeTaskLabel: '',
  activeTaskBackgrounded: false,
  activeTaskOrigin: null,
  archivePreparationToken: null,
  activeGenerationTasks: new Map(),
  activeModeBuildScopes: new Set(),
  activeAdvBulkScopes: new Set(),
  activeArchiveTargetReservations: new Map(),
  activeCgImageTasks: new Map(),
  cgImageLifecycleEpoch: 0,
  avatarDialogueRequestEpoch: 0,
  activeAvatarDialogue: null,
  activeProviderRequestCount: 0,
  providerRequestQueue: [],
  butterflyTransitionTimer: 0,
  archiveOverviewCache: { key: '', fetchedAt: 0, items: [] },
  archiveOverviewPromise: null,
  archiveOverviewPromiseKey: '',
  archiveOverviewAllowedChats: new Set(),
  archiveOverviewKnownArchives: new Map(),
  archiveOverviewLastKey: '',
  chooserRefreshTimer: 0,
  memoryPreflightCache: new Map(),
  deferredChatCommits: core_deferredCommitStore.createDurableDeferredCommitMap(),
  archiveLibraryCharacterKey: '',
  archiveCharacterRelationSelection: '',
  relationSelectedKey: '',
  activeArchiveSnapshot: null,
  activeArchiveReadOnly: true,
  archiveSnapshotCache: new Map(),
  connectionModelCache: new Map(),
  connectionModelRequestEpochs: new Map(),
  runtimeSessionCache: new Map(),
  cacheHydrationPromises: new Map(),
  cacheHydrationErrors: new Map(),
  cachePersistTimers: new Map(),
  pendingCompressedCacheWrites: new Map(),
  cacheCommitSequences: new Map(),
  cachePersistChains: new Map(),
  archiveCommitChains: new Map(),
  archiveDeletionFences: new Set(),
  archiveTargetTaskEpochs: new Map(),
  calendarTagFilters: new Map(),
  usableMessageCountCache: new Map(),
};
